service: calorie-calculator

# can't have plugins in another file, else they can't be used in our local dev env. (and probably in aws too)
plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-stage-manager
  - serverless-plugin-bind-deployment-id
  - serverless-pseudo-parameters
  - serverless-offline-python # @TODO: switch this to serverless-offline when issues are resolved
  - serverless-aws-documentation

package:
  exclude:
    # Exclude everything that does not NEED to be in AWS
    - .circleci/**
    - .serverless/**
    - .gitignore
    - docs/**
    - node_modules/**
    - ops/**
    - tests/**
    - Makefile
    - package*
    - README.md
    - requirements.txt

custom:
  wsgi:
    app: src/functions/api.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
    slim: true # Removes all tests, information, and caches from the installed packages
    usePipenv: true
  stages: # Blocks deployment if whatever is passed in --stage CLI option is not in this array
    - local
    - dev
    - staging
    - prod

provider:
  name: aws
  runtime: python3.6
  region: 'us-east-1'
  stage: ${opt:stage, 'dev'}
  logRetentionInDays: 2 # Just being cheap here
  apiKeys:
    - ${self:service}-${self:provider.stage}-test

functions:
  api:
    handler: wsgi_handler.handler
    timeout: 10
    events:
      - http:
          path: calculate/run
          method: get
          private: true
          documentation:
            summary: Calculates calories burned while running
            # @TODO: fill in the rest
