service: calorie-calculator

# can't have plugins in another file, else they can't be used in our local dev env. (and probably in aws too)
plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-stage-manager
  - serverless-plugin-bind-deployment-id
  - serverless-pseudo-parameters
  - serverless-offline-python # @TODO: switch this to serverless-offline when issues are resolved
  - serverless-aws-documentation

package:
  exclude:
    # Exclude everything that does not NEED to be in AWS
    - .circleci/**
    - .serverless/**
    - .gitignore
    - docs/**
    - node_modules/**
    - ops/**
    - tests/**
    - Makefile
    - package*
    - README.md
    - requirements.txt

custom:
  wsgi:
    app: src/functions/api.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
    slim: true # Removes all tests, information, and caches from the installed packages
    usePipenv: true
  stages: # Blocks deployment if whatever is passed in --stage CLI option is not in this array
    - local
    - dev
    - staging
    - prod
  documentation:
    info:
      version: "0.1" # This must get updated in order for API Gateway to pick up changes
      title: Calorie calculator
      description: This API calculates calories burned during an activity
      contact:
        name: Colin Busse
      models:
        -
          name: CalculateRunValidResponse
          description: This is a successful response
          contentType: "application/json"
          # @TODO:
          #schema: ${file(src/functions/api/schema/response/calculate_run_success.json)}
        -
          name: CalculateRunBadRequestResponse
          description: This is an error response due to a bad request
          contentType: "application/json"
          # @TODO:
          #schema: ${file(src/functions/api/schema/response/calculate_run_badrequest.json)}

provider:
  name: aws
  runtime: python3.6
  region: 'us-east-1'
  stage: ${opt:stage, 'dev'}
  logRetentionInDays: 2 # Just being cheap here
  apiKeys:
    - ${self:service}-${self:provider.stage}-test

functions:
  api:
    handler: wsgi_handler.handler
    timeout: 10
    events:
      - http:
          path: calculate/{activity}
          method: get
          private: true
          documentation:
            summary: Calories burned running
            description: Calculates calories burned while running
            produces:
              - application/json
            requestHeaders:
              -
                name: x-api-key
                description: API key
            queryParams:
              -
                name: distance
                description: Distance ran (in miles)
              -
                name: hours
                description: The number of hours spent running
              -
                name: minutes
                description: The number of minutes spent running
              -
                name: seconds
                description: The number of seconds spent running
              -
                name: weight
                description: The bodyweight (in pounds) of the athlete
            methodResponses:
              - statusCode: 200
                responseBody:
                  description: A successful response object
                responseModels:
                  "application/json": CalculateRunValidResponse
              - statusCode: 400
                responseBody:
                  description: An unsuccessful response object due to a bad request
                responseModels:
                  "application/json": CalculateRunBadRequestResponse
