version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6-node
    working_directory: ~/app/serverless-calorie-calculator
    steps:
      - checkout
      - run:
          name: Install serverless
          command: sudo npm install -g serverless@1.42.3
      - run:
          name: Install npm modules
          command: npm install
      - run:
          name: Install pipenv
          command: sudo pip install pipenv
      - run:
          name: Install python modules
          command: sudo pipenv install --system
  unit_test:
    docker:
      - image: circleci/python:3.6-node
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: pytest tests/unit

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - unit_test:
          requires:
            - build
          filters:
            branches:
              only: master
