version: 2

references:
  install_serverless: &install_serverless
    run:
      name: Install serverless
      command: sudo npm install -g serverless@1.42.3

  install_npm_modules: &install_npm_modules
    run:
      name: Install npm modules
      command: npm install

  install_pipenv: &install_pipenv
    run:
      name: Install pipenv
      command: sudo pip install pipenv

  install_python_modules: &install_python_modules
    run:
      name: Install python modules
      command: sudo pipenv install --system --dev

  unit_test: &unit_test
    run:
      name: Run unit tests
      command: pytest tests/unit

jobs:
  build_and_unit_test:
    docker:
      - image: circleci/python:3.6-node
    steps:
      - checkout
      - *install_serverless
      - *install_npm_modules
      - *install_pipenv
      - *install_python_modules
      - *unit_test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_unit_test:
          filters:
            branches:
              only: master
