version: 2

references:
  install_node: &install_node
    run:
      name: Install node
      command: curl -sL https://rpm.nodesource.com/setup_8.x | bash ; yum install -y nodejs

  install_serverless: &install_serverless
    run:
      name: Install serverless
      command: npm install -g serverless@1.42.3

  install_npm_modules: &install_npm_modules
    run:
      name: Install npm modules
      command: npm install

  install_pipenv: &install_pipenv
    run:
      name: Install pipenv
      command: pip install pipenv

  install_python_modules: &install_python_modules
    run:
      name: Install python modules
      command: pipenv install --system --dev

  unit_test: &unit_test
    run:
      name: Run unit tests
      command: pytest tests/unit

  robot_tests_prod: &robot_tests_prod
    run:
      name: Run robot tests on production
      command: tests/acceptance/runtests.sh prod

  store_robot_results_prod: &store_robot_results_prod
    store_artifacts:
      path: tests/acceptance/results/
      destination: acceptance/prod/

  sls_deploy_staging: &sls_deploy_staging
    run:
      name: Deploy to staging
      command:  npx serverless deploy --stage staging --conceal
      environment:
        - SLS_DEBUG: 1

  sls_deploy_prod: &sls_deploy_prod
    run:
      name: Deploy to production
      command:  npx serverless deploy --stage prod --conceal
      environment:
        - SLS_DEBUG: 1

jobs:
  deploy_staging:
    docker:
      - image: lambci/lambda:build-python3.6
    steps:
      - checkout
      - *install_node
      - *install_serverless
      - *install_npm_modules
      - *install_pipenv
      - *install_python_modules
      - *unit_test
      - *sls_deploy_staging

  deploy_prod:
    docker:
      - image: lambci/lambda:build-python3.6
    steps:
      - checkout
      - *install_node
      - *install_serverless
      - *install_npm_modules
      - *install_pipenv
      - *install_python_modules
      - *unit_test
      - *sls_deploy_prod
      - *robot_tests_prod
      - *store_robot_results_prod

workflows:
  version: 2
  build_and_test:
    jobs:
      - deploy_staging:
          filters:
            branches:
              only: staging
      - deploy_prod:
          filters:
            branches:
              only: master
